/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio.$category'
import { Route as DiarioSlugRouteImport } from './routes/diario.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PortfolioRoute,
} as any)
const DiarioSlugRoute = DiarioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiarioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diario': typeof DiarioRouteWithChildren
  '/notas': typeof NotasRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/sobre': typeof SobreRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diario': typeof DiarioRouteWithChildren
  '/notas': typeof NotasRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/sobre': typeof SobreRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/diario': typeof DiarioRouteWithChildren
  '/notas': typeof NotasRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/sobre': typeof SobreRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/diario'
    | '/notas'
    | '/portfolio'
    | '/sobre'
    | '/diario/$slug'
    | '/portfolio/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/diario'
    | '/notas'
    | '/portfolio'
    | '/sobre'
    | '/diario/$slug'
    | '/portfolio/$category'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/diario'
    | '/notas'
    | '/portfolio'
    | '/sobre'
    | '/diario/$slug'
    | '/portfolio/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  DiarioRoute: typeof DiarioRouteWithChildren
  NotasRoute: typeof NotasRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/diario/$slug': {
      id: '/diario/$slug'
      path: '/$slug'
      fullPath: '/diario/$slug'
      preLoaderRoute: typeof DiarioSlugRouteImport
      parentRoute: typeof DiarioRoute
    }
  }
}

interface DiarioRouteChildren {
  DiarioSlugRoute: typeof DiarioSlugRoute
}

const DiarioRouteChildren: DiarioRouteChildren = {
  DiarioSlugRoute: DiarioSlugRoute,
}

const DiarioRouteWithChildren =
  DiarioRoute._addFileChildren(DiarioRouteChildren)

interface PortfolioRouteChildren {
  PortfolioCategoryRoute: typeof PortfolioCategoryRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCategoryRoute: PortfolioCategoryRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  DiarioRoute: DiarioRouteWithChildren,
  NotasRoute: NotasRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
